---
services:
  suwayomi:
    image: ghcr.io/suwayomi/suwayomi-server:stable
    container_name: komik-reader-suwayomi
    environment:
      - TZ=Asia/Jakarta
      - EXTENSION_REPOS=["https://raw.githubusercontent.com/keiyoushi/extensions/repo/index.min.json"]
    volumes:
      - ./data:/home/suwayomi/.local/share/Tachidesk
    ports:
      - "4567:4567"
    restart: unless-stopped